version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: order_api_auth_db
    environment:
      POSTGRES_DB: order_api_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
