version: "3.8"

services:
  # Test database
  test-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: order_cart_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data:
